Переключение состояний карточек
OneBootcamp-1-0/itsdone-1 pull request #17
Opened 2020-09-14 17:10 UTC by JohnC27

fixes #15

2020-09-14 17:13 UTC, JohnC27 commented on src/index.js
> +rerenderDOM(state.cards);
I know, супер неоптимизированно, но единственное, что получилось реализовать *_*

2020-09-14 17:58 UTC, kicumkicum requested changes

2020-09-14 17:58 UTC, kicumkicum commented on src/components/Board/Card/Card.jsx
> +    onCardEdit(Number(card.dataset.id), card.dataset.done === 'true' ? false : true);
Видимо тут промах в структуре данных. Зачем хранить `"true"` когда можно `true`. Тогда бы етот код изменился на `onCardEdit(Number(card.dataset.id), !card.dataset.done);`

UPD. А, понял. Там строка, потому что данные берутся в в доме. Но зачем их брать из дома, когда нужная инфа хранится в переменной `isDone`?

2020-09-14 17:58 UTC, kicumkicum commented on src/index.js
> +rerenderDOM(state.cards);
Для старта пойдет. Но можно дать имя `renderDOM`. Потому что мы просто рендерим дом)

В будущем ето можно заменить на стейт менеджер, типа редакс. 

Но в принципе, можно избавиться от `rerenderDOM`, если объявить `onCardEdit` внутри `App`. Возможно ето может конфликтовать в чем-то с тем, что я говорил или писал, но разработка часто заставляет идти на компромис с чем-нибудь.

Примите решение самостоятельно, только напишите какой вариант выберете комментом, чтобы я знал ждать или не ждать. Но при етом помните, что когда придет стейт-менеджер, то он в любом случае привнесет коррективы (ето может случиться в следующем спринте)

2020-09-14 17:58 UTC, kicumkicum commented on src/components/Header/Header.jsx
> +      canbanLinkRef.current.dataset.activeLink = "true";
Тут хотелось бы так-же получать данные из данных, а не дома

2020-09-15 10:35 UTC, mariaYunB commented on src/index.js
> +rerenderDOM(state.cards);
Решили не избавляться от `renderDOM`

2020-09-15 11:08 UTC, merged

2020-09-15 11:08 UTC, kicumkicum commented
Я забыл нажать апрув, но он есть)