Edit mode
OneBootcamp-1-0/itsdone-1 pull request #21
Opened 2020-09-16 16:07 UTC by whoisdaria

2020-09-16 16:16 UTC, kicumkicum requested changes

2020-09-16 16:16 UTC, kicumkicum commented on src/index.js
> +      return card
С первого взгляда с телефона все норм. Но расстреляли ; и поехали отступы где-то выше. Позже проведу более детальное ревью

2020-09-16 21:07 UTC, kicumkicum commented
- [ ] Баг: Клик по карточке редактирования переводит ее в режим просмотра. Из-за етого я не могу выделить текст и выбрать дату

2020-09-16 21:15 UTC, kicumkicum requested changes
Есть одно спорное решение и баг

2020-09-16 21:15 UTC, kicumkicum commented on src/components/Board/Canban/Column/Column.jsx
> +    onCardEdit(Number(cardId), {status: status});
отступ

2020-09-16 21:15 UTC, kicumkicum commented on src/components/Board/Card/Card.jsx
> +
Лишняя строка

2020-09-16 21:15 UTC, kicumkicum commented on src/components/Board/Card/Card.jsx
> +return isEdit ? <EditCard setIsEdit={setIsEdit} id={id} onCardEdit={onCardEdit} date={date} title={title} text={text}/> : <div data-card={true} id={id} onClick={onCardClick} draggable={true} onDragSt
Если строка получается длинной, то надо переносить. Особенно при условном рендеринге. Нужно получить  что-то вроде
```js
return (
  isEdit
    ? <EditCard />
    : <Card />
);
```

Пропсы я не написал, но их конечно тоже нужно.

2020-09-16 21:15 UTC, kicumkicum commented on src/components/Board/Card/Card.jsx
> +return isEdit ? <EditCard setIsEdit={setIsEdit} id={id} onCardEdit={onCardEdit} date={date} title={title} text={text}/> : <div data-card={true} id={id} onClick={onCardClick} draggable={true} onDragSt
О, тут оказывается вон че... Почему вы решили использовать `EditCard` внутри `Card`? Лучше бы чтобы ето условие было снаружи. Чтобы код получился в комменте выше

2020-09-16 21:15 UTC, kicumkicum commented on src/index.js
> +  let foundCard = state.cards.find(card => {
Почему `let`? Переменная же не переписывается вроде

2020-09-17 14:36 UTC, kicumkicum approved these changes

2020-09-17 14:36 UTC, kicumkicum commented on src/components/Board/Canban/Column/Column.jsx
> +    document.querySelector('#root').addEventListener('click', (e) => {
Когда работаешь с реактор, нужно стараться не использовать Dom. В данном случае нужно подписаться через пропсы onClick.

2020-09-17 14:36 UTC, kicumkicum commented on src/components/Board/Grid/Grid.jsx
> +  const [isEdit, setIsEdit] = useState({
С приставки is начинаются булевы объекты. Тут у тебя сущность, ее можно назвать editCard

2020-09-17 14:37 UTC, kicumkicum requested changes

2020-09-17 14:37 UTC, kicumkicum commented on src/components/Board/Canban/Column/Column.jsx
> +  const [isEdit, setIsEdit] = useState({
.

2020-09-17 14:38 UTC, kicumkicum commented
Нужно подправить два момента, то будет все хорошо

2020-09-18 08:52 UTC, mariaYunB commented on src/components/Board/Canban/Column/Column.jsx
> +    document.querySelector('#root').addEventListener('click', (e) => {
Убрали фунцию в следующем пр

2020-09-18 18:49 UTC, kicumkicum approved these changes

2020-09-18 18:49 UTC, merged