Теги
OneBootcamp-1-0/itsdone-1 pull request #31
Opened 2020-09-21 13:19 UTC by mariaYunB

2020-09-21 13:56 UTC, kicumkicum requested changes
Очень хорошее первое приближение. Давай еще оживим етот код и будет вообще отлично

2020-09-21 13:56 UTC, kicumkicum commented on src/components/Board/Card/TagCloud.jsx
> +        <li className={css.tag_cloud__item}>#2-points</li>
Вышло хорошо, но можно лучше. Тут мы взяли и захардкодили наши теги. Я не помню, что мы обсуждали по поводу списка тегов, но в любом случае лучше делать его динамическим.
Во первых, потому трудозатраты на создание одинаковые.
Во вторых, потому что они все равно будут динамическими (браться из задачи) и придется вносить новые изменения.

2020-09-21 13:56 UTC, kicumkicum commented on src/components/Board/Card/Card.jsx
> +      {isTagCloud ? <TagCloud /> : null}
Етот условный рендеринг выглядит избыточно. Давай всегда рендерить `TagCloud` и передавать в него массив тегов через пропс. Если `TagCloud` в итоге будет рендерить пустой контейнер для тегов, то ничего страшного. Но если что-то куда-то уедет, то он всегда может отрендерить `null`

2020-09-21 13:56 UTC, kicumkicum commented on src/components/Board/Card/Card.jsx
> +      {isTagCloud ? <TagCloud /> : null}
Теги нужно брать из карточки, но для етого нужно расширить наш json - добавить в структуру карточки поле `tags: []`  и для одной-двух карточек накидать тегов.

2020-09-22 09:07 UTC, mariaYunB commented
Что-то как-то не получается, предположительно из-за того, что tags в пропсах — массив, и я делаю с ним что-то не так ¯\_(ツ)_/¯

2020-09-22 12:21 UTC, kicumkicum requested changes
Все классно, но сломалось приложение на канбане
![image](https://user-images.githubusercontent.com/5058981/93881162-3aa8b000-fce7-11ea-9a68-4c93e4733913.png)

2020-09-22 12:48 UTC, kicumkicum approved these changes

2020-09-22 12:48 UTC, merged