Redux
OneBootcamp-1-0/itsdone-1 pull request #37
Opened 2020-09-22 17:27 UTC by JohnC27

2020-09-22 17:30 UTC, JohnC27 commented on src/redux/tasksReducer.js
> +export const actions = {
Получилось много дублирующегося кода, но не знаю, можно ли объеденить или вынести одинаковые куски?

2020-09-22 17:31 UTC, JohnC27 commented on src/redux/tasksReducer.js
> +export const actions = {
Получилось много дублирующегося кода, но не знаю, можно ли объеденить или вынести одинаковые куски.

2020-09-22 17:59 UTC, JohnC27 commented on src/redux/tasksReducer.js
> +  switch (action.type) {
Тут возникла дилемма: 
1. Сейчас я делю так, что сервер у себя в db кладет изменения и возвращает полностью новый массив карточек, и соответственно в любых кейсах я просто весь старый массив заменяю на новый.
2. Но есть и второй вариант: 
  - При обновлении карточки возвращать лишь её, при создании новой - тоже возвращать лишь её с сервера, и тогда если надо создать, то в reducer push'ить новую, а если действие - обновить, то заменять в массиве только старую на новую.
И такой вариант вроде оптимизированнее, но мне не нравиться то, что логика на сервере и в reducer'е будет дублироваться и может случайно пойти по разным сценариям.

2020-09-22 20:27 UTC, kicumkicum requested changes
Использование редак-тулкита не обязательно - по желанию

2020-09-22 20:27 UTC, kicumkicum commented on src/redux/tasksReducer.js
> +import tasksAPI from '../api/tasks-api.js';
файлы мы именуем в снек-кейсе

2020-09-22 20:27 UTC, kicumkicum commented on src/redux/tasksReducer.js
> +  switch (action.type) {
Чаще используется вариант 2. С одной стороны потому что данных в реальных приложениях много. С другой потому что так вещает концепция REST Full. Обновил сущность - получил сущность.

Но можно использовать и вариант номер 1. Совсем ничего не возвращать так себе идея, потому что ето превращается в оптимистичное программирование. Жить можно, но возможны побочные действия

2020-09-22 20:27 UTC, kicumkicum commented on src/redux/tasksReducer.js
> +export const actions = {
Добро пожаловать в редакс 😈

2020-09-22 20:27 UTC, kicumkicum commented on src/redux/tasksReducer.js
> +export const actions = {
Можно сократить количество кода, если использовать редакс-тулкит. Он позволяет весь етот бойлерплейт спрятать под капот. Посмотри на него.

2020-09-22 20:27 UTC, kicumkicum commented on src/redux/tasksReducer.js
> +// Thunks
Такие комменты для организации кода не оч идея. Используй для етого лучше неймспейс. Есть концепция ducks, которая предлагает именовать асинхронные екшены операциями. И можно сделать
```js
export const Operation = {
  requestTasks() {},
  addTask() {},
};
```

2020-09-23 15:13 UTC, JohnC27 commented on src/redux/tasksReducer.js
> +export const actions = {
Чо-то посмотрел на тулкит и решил, что потом как-нибудь познакомлюсь c ним поближе: ]

2020-09-23 15:14 UTC, JohnC27 commented on src/redux/tasksReducer.js
> +  switch (action.type) {
Переделал под 2ой вариант

2020-09-23 17:36 UTC, kicumkicum commented
Что-то говорит конфликтует с мастером

2020-09-23 18:12 UTC, kicumkicum commented
Надо было просто мне сказать, что я не прав. Сорян) У нас камелКейс
![image](https://user-images.githubusercontent.com/5058981/94052330-74f67800-fde1-11ea-8e75-5eb8a2fc94ef.png)

2020-09-23 21:29 UTC, kicumkicum approved these changes

2020-09-23 21:29 UTC, merged