Базовый лэйаут проекта
OneBootcamp-1-0/itsdone-1 pull request #5
Opened 2020-09-09 15:02 UTC by JohnC27

fixes #4

2020-09-09 15:07 UTC, JohnC27 commented
P.S. Коммиты почти только мои, тк мы кодили через vs code life share и там только создатель конфы может коммитить (насколко мы поняли), а так то все работали )

2020-09-09 17:36 UTC, kicumkicum commented
Если вдруг захочется, чтобы комиты отображали реального автора, то при коммите через консоль можно передать параметр `--author`

2020-09-09 17:37 UTC, kicumkicum commented
Посмотрел код - выглядит все хорошо, крутяг! 
Через несколько часов доберусь до компа и с него ещё посмотрю

2020-09-09 21:52 UTC, kicumkicum requested changes
Все очень круто! Завтра расскажу почему) А сейчас можно минорные замечания пофиксить

2020-09-09 21:52 UTC, kicumkicum commented on src/App.jsx
> +import ReactDOM from 'react-dom';
Он тут не используется

2020-09-09 21:52 UTC, kicumkicum commented on src/App.jsx
> +import ReactDOM from 'react-dom';
Можно подключить в линтере правило, которое проверяет неиспользуемые переменные

2020-09-09 21:52 UTC, kicumkicum commented on src/components/Board/Board.jsx
> +import ReactDOM from 'react-dom';
А, вы его во все компоненты добавили. Ето не нужно. Нужен только `React`. А `react-dom` нужен только там, где явно вызывается.

2020-09-09 21:52 UTC, kicumkicum commented on src/components/Board/Card/Card.jsx
> +const Card = () => <div className={css.card}>Не забыть выполнить важную задачу</div>;
Луше не сокращать синтаксис до одной строки. Ето мешаеть, когда хочешь какой-нибудь консоль лог воткнуть или дебаггер поставить. Но в первую очередь сложнее читать

2020-09-10 10:53 UTC, kicumkicum approved these changes

2020-09-10 10:53 UTC, merged