Сохранение тегов
OneBootcamp-1-0/itsdone-1 pull request #59
Opened 2020-09-29 17:58 UTC by JohnC27

2020-09-29 22:46 UTC, kicumkicum requested changes

2020-09-29 22:46 UTC, kicumkicum commented on src/App.jsx
> +        else if (!allTags[tagName]) {
уехали

2020-09-29 22:46 UTC, kicumkicum commented on src/App.jsx
> +        dispatch(operations.updateTask({ id: card.id, tags: { ...card.tags, ...newTags } }));
Опасно. Ты бежишь в большом цикле и дергаешь сетевой запрос. Потенциально он может отработать очень большое количество раз. Лучше бы его дергать на конкретное действие пользователя

2020-09-30 11:16 UTC, mariaYunB approved these changes

2020-09-30 11:28 UTC, whoisdaria approved these changes

2020-09-30 12:02 UTC, merged