Валидация title
OneBootcamp-1-0/itsdone-1 pull request #63
Opened 2020-09-30 16:57 UTC by mariaYunB

2020-09-30 19:18 UTC, JohnC27 requested changes

2020-09-30 19:18 UTC, JohnC27 commented on src/components/Board/Card/EditCard.jsx
> +        document.querySelector('input[data-title=true]').setCustomValidity('must be filled')
Гуд, только тут лучше сделать с помощью `ref` получение элемента

2020-09-30 19:18 UTC, JohnC27 commented on src/components/Board/Card/EditCard.jsx
> +        document.querySelector('input[data-title=true]').setCustomValidity('');
и тут

2020-09-30 19:18 UTC, JohnC27 approved these changes

2020-10-01 08:01 UTC, whoisdaria approved these changes

2020-10-01 08:01 UTC, whoisdaria commented on src/components/Board/Card/Card.css
> +  margin-top: 20px;
а почему не auto? они же скачут

2020-10-01 09:34 UTC, merged