Фикс hide completed
OneBootcamp-1-0/itsdone-1 pull request #85
Opened 2020-10-06 15:49 UTC by JohnC27

fixes #78

2020-10-06 16:06 UTC, mariaYunB commented
Есть небольшая проблема - по макету и по смыслу кнопки hide completed нет в канбане

2020-10-07 21:16 UTC, kicumkicum requested changes

2020-10-07 21:16 UTC, kicumkicum commented on src/components/Header/Header.jsx
> +      {activeLink === 'canban' ? null : <button onClick={onButtonShowClick} type='button' className={css.button_show}>{showCompletedBtn ? 'Hide completed' : 'Show completed'}</button>}
Длинная сложная строка. Можно так
```suggestion
      {
        activeLink === 'canban'
          ? null
          : <button onClick={onButtonShowClick} type='button' className={css.button_show}>{showCompletedBtn ? 'Hide completed' : 'Show completed'}</button>
      }
```

2020-10-08 16:55 UTC, JohnC27 commented
_Merge me pls_

2020-10-08 18:59 UTC, merged